# Generated by Django 2.1.5 on 2021-09-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postal', '0003_auto_20210925_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subject',
            field=models.TextField(blank=True, null=''),
        ),
    ]
