# Generated by Django 2.1.5 on 2021-09-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='complete',
        ),
        migrations.AddField(
            model_name='evidence',
            name='source',
            field=models.URLField(default='n/a', null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='speaker',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
