# Generated by Django 2.1.5 on 2021-10-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate_project', '0003_auto_20210925_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
