# Generated by Django 3.2.7 on 2021-09-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='summary',
        ),
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
    ]
