# Generated by Django 3.2.7 on 2021-09-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210923_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='email',
            field=models.EmailField(default='n/a', max_length=254, null=True),
        ),
    ]
